---
- name: Docker
  hosts: aws-okd
  become: yes
  tasks:
  - name: Docker login
    docker_login:
     username: cccr3team
     password: cccr3team
     
  - name: Docker tag  
    command: docker tag docker-registry.defaults.svc:5000/test3/nodejs-mongodb-example cccr3team/nodejs-mongodb-example
      
  - name: Docker push
    command: docker push cccr3team/nodejs-mongodb-example
