---
- name: OKD Master
  become: yes
  hosts: okd
  vars_files:
    - vars.yml
  tasks:
  - name: Package install
    yum:
      name: 
        - bind
        - net-tools
        - NetworkManager
        - firewalld
      state: present
      
  - name: Set a hostname
    hostname:
      name: "{{ okd['hostname'] }}"

  - name: Set a sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "{{ packet_forward }}"

  - name: Hosts file to Template
    template:
      src: hosts
      dest: /etc/hosts 

  - name: Set a DNS
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    with_items:
      - DNS1={{ okd['network']['dns1'] }}
      - DNS2={{ okd['network']['dns2'] }}
      - NM_CONTROLLED=yes
      - PEERDNS=yes
            
  - name: Restart Network service
    service:
      name: network
      state: restarted
            
  - name: Resolv file to Template
    template:
      src: resolv.conf
      dest: /etc/resolv.conf
      
  - name: Start NetworkManager Service
    service:
      name: NetworkManager
      state: restarted
