---
- name: ssh-test
  become: yes
  hosts: bastion
  tasks:
  - name: ssh-keygen
    command : ssh-keygen -q -b 2048 -t rsa -N "" -f ~/.ssh/id_rsa -y
    ignore_errors: yes
    run_once: true
    
  - name: SSH-KEY Copy3
    command: sshpass -p toor ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no localhost
    
  - name: ssh-key copy4
    command: sshpass -p toor ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@192.168.122.139
    
  - name: h2 
    set_fact:
      bastion_ip: "{{ ansible_eth0.ipv4.address }}"
      bastion_fqdn: "{{ ansible_nodename }}"

  - name: h3
    setup:
    delegate_to: okd
  - name: h4
    set_fact:
      okd_ip: "{{ ansible_eth0.ipv4.address }}"
      okd_fqdn: "{{ ansible_nodename }}"

  - name: template hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts 
