---
- name: Bastion
  become: yes
  hosts: bastion
  vars_files:
    - vars.yml
  tasks:
  - name: Set a hostname
    hostname:
      name: "{{ bastion['hostname'] }}"

  - name: Hosts file to Template
    template:
      src: hosts.j2
      dest: /etc/hosts 

  - name: Package install
    yum:
      name:
        - epel-release
        - bind
        - net-tools
      state: present
    
  - name: Set a DNS
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    with_items:
      - DNS1={{ bastion['network']['dns1'] }}
      - DNS2={{ bastion['network']['dns2'] }}

  - name: Packet forwarding
    lineinfile:
      path: /etc/sysctl.conf
      line: "{{ packet_forward }}"
      
  - name:  Restart Network service
    service:
      name: network
      state: restarted Restart 
    
  - name: Set a Named file
    replace:
      path: /etc/named.conf
      regexp: "{{ item['regexp'] }}"
      replace: "{{ item['replace'] }}"
    with_items:
      - { regexp: "({ 127.0.0.1; };)$", replace: "{ any; };" }
      - { regexp: "({ ::1; };)$", replace: "{ any; };" }
      - { regexp: "({ localhost; };)$", replace: "{ any; };" }
    
  - name: Zone file to Template
    template:
      src: cccr3.com.zone.j2
      dest: /var/named/cccr3.com.zone
      
  - name: Start Named Service
    service:
      name: named
      state: started
      enabled: yes
        
  - name: 53 Port enabled
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items:
      - "{{ bastion['port'] }}/tcp"
      - "{{ bastion['port'] }}/udp"
      
  - name: Start NetworkManager Service
    service:
      name: NetworkManager
      state: restarted
