- name: Master
  become: yes
  hosts: okd
  tasks:
  - name: package install
    yum:
      name: 
        - bind
        - net-tools
        - NetworkManager
        - firewalld
      state: present

  - name: okd set_fact
    set_fact:
      okd_ip: "{{ ansible_eth0.ipv4.address }}"
      okd_fqdn: "{{ ansible_nodename }}"

  - name: delegate_to
    setup:
    delegate_to: bastion
  - name: set_fact
    set_fact:
      bastion_ip: "{{ ansible_eth0.ipv4.address }}"
      bastion_fqdn: "{{ ansible_nodename }}"

  - name: Static IP setting
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: "^BOOTPROTO="
      line: BOOTPROTO="static"
      
  - name: Static IP setting
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    with_items:
      - IPADDR={{ okd_ip }}
      - NETMASK={{ ansible_eth0.ipv4.netmask }}
      - GATEWAY={{ ansible_default_ipv4.gateway }}
      - DNS1={{ bastion_ip }}
      - DNS2=8.8.8.8
      - NM_CONTROLLED=yes
      - PEERDNS=yes
            
  - name: Template DNS
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
      
  - name: Add sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "net.ipv4.ip_forward=1"
      
  - name: Network service Restart
    service:
      name: network
      state: restarted
      
  - name: Start to NetworkManager Service
    service:
      name: NetworkManager
      state: restarted
      
      
      
      
     
