---
- name: ssh-test
  become: yes
  hosts: bastion
  tasks:
  - name: ssh-keygen
    command : ssh-keygen -q -b 2048 -t rsa -N "" -f ~/.ssh/id_rsa
    ignore_errors: yes
    run_once: true
    
    
