- name: Master
  become: yes
  hosts: okd
  tasks:
  vars_file: vars.yml
  - name: package install
    yum:
      name: 
        - bind
        - net-tools
        - NetworkManager
        - firewalld
      state: present

  - name: okd set_fact
    set_fact:
      okd_ip: "{{ ansible_eth0.ipv4.address }}"
      okd_fqdn: "{{ ansible_nodename }}"

  - name: delegate_to
    setup:
    delegate_to: bastion
  - name: set_fact
    set_fact:
      bastion_ip: "{{ ansible_eth0.ipv4.address }}"
      bastion_fqdn: "{{ ansible_nodename }}"

  - name: Add sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: {{ bastion['packet_forward'] }}

  - name: Start to NetworkManager Service
    service:
      name: NetworkManager
      state: restarted

  - name: Static IP setting
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: "^BOOTPROTO="
      line: BOOTPROTO={{ type }}
      
  - name: Static IP setting
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    with_items:
      - IPADDR={{ okd['network']['ip'] }}
      - NETMASK={{ okd['network']['netmask'] }}
      - GATEWAY={{ okd['network']['gateway'] }}
      - DNS1={{ okd['network']['dns1'] }}
      - DNS2={{ okd['network']['dns2'] }}
      - NM_CONTROLLED=yes
      - PEERDNS=yes
            
  - name: Network service Restart
    service:
      name: network
      state: restarted
            
  - name: Template DNS
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf

      
      
      
     
