---
- name: ssh-test
  become: yes
  hosts: bastion
  vars_files:
    - vars.yml
  tasks:
  - name: Set a hostname
    hostname:
      name: "{{ bastion['hostname'] }}"

  - name: template hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts 

  - name: epel-release, bind, net-tools install
    yum:
      name:
        - epel-release
        - bind
        - net-tools
      state: present
    
  - name: Static IP setting
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    with_items:
      - DNS1={{ bastion['network']['dns1'] }}
      - DNS2={{ bastion['network']['dns2'] }}

  - name: Packet forwarding
    lineinfile:
      path: /etc/sysctl.conf
      line: "{{ packet_forward }}"
      
  - name: Network service Restart
    service:
      name: network
      state: restarted
    
  - name: Bastion replace DNS1
    replace:
      path: /etc/named.conf
      regexp: "{{ item['regexp'] }}"
      replace: "{{ item['replace'] }}"
    with_items:
      - { regexp: "({ 127.0.0.1; };)$", replace: "{ any; };" }
      - { regexp: "({ ::1; };)$", replace: "{ any; };" }
      - { regexp: "({ localhost; };)$", replace: "{ any; };" }
    
  - name: Temaplate zone file
    template:
      src: cccr3.com.zone.j2
      dest: /var/named/cccr3.com.zone
      
  - name: Start to Named Service
    service:
      name: named
      state: started
      enabled: yes
        
  - name: 53 Port enabled
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items:
      - "{{ bastion['port'] }}/tcp"
      - "{{ bastion['port'] }}/udp"
      
  - name: Start to NetworkManager Service
    service:
      name: NetworkManager
      state: restarted
