---
- name: Job for Bastion
  become: yes
  hosts: controller
  tasks:
  - name: Bastionreplace DNS1
    replace:
      path: /etc/named.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: "({ 127.0.0.1; };)$", replace: "{ any; };" }
      - { regexp: "({ ::1; };)$", replace: "{ any; };" }
      - { regexp: "({ localhost; };)$", replace: "{ any; };" }
      
  - name: Bastion replace DNS2
    lineinfile:
      path: /etc/named.rfc1912.zones
      line: "{{ item }}"
    with_items:
      - "zone \"cccr3.com\" IN {"
      - "        type master;"
      - "        file \"cccr3.com.zone\";"
      - "        allow-update { none; };"
      - "}; "

  - name: Create zone file
    lineinfile:
      path: /var/named/cccr3.com.zone
      create: yes
      line: "{{ item }}"
    with_items:
      - "$TTL 3H"
      - "@ IN SOA ns.cccr3.com. root.cccr3.com. ( "
      - " 0 ; serial"
      - " 1D ; refresh"
      - " 1H ; retry"
      - " 1W ; expire"
      - " 3H ) ; minimum"
      - " IN NS ns.cccr3.com."
      - "ns IN A 192.168.122.3"
      - "* IN A 192.168.122.244"
      - "okd IN A 192.168.122.244"
      
  - name: Start to Named Service
    service:
      name: named
      state: started
      enabled: yes
        
  - name: 53 Port enabled
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_item:
      - "53/tcp"
      - "53/udp"
