---
- name: Job for Bastion
  become: yes
  hosts: controller
  tasks:
  - name: Bastion replace DNS
    replace:
      path: /etc/named.conf
      regexp: 127.0.0.1;
      replace: any;

    replace:
      path: /etc/named.conf
      regexp: ::1;
      replace: any;

    replace:
      path: /etc/named.conf
      regexp: localhost;
      replace: any;
