---
- name: Job for Bastion
  become: yes
  hosts: controller
  tasks:
  - name: Bastion replace DNS1
    replace:
      path: /etc/named.conf
      regexp: {{ item.regexp }}
      replace: {{ item.replace }}
    with_items:
      - { regexp: "({ 127.0.0.1; };)$", replace: "{ any; };" }
      - { regexp: ""({ ::1; };)$"", replace: "{ any; };" }
      - { regexp: "({ 127.0.0.1; };)$", replace: "{ any; };" }
