---
- name: Job for Bastion
  become: yes
  hosts: controller
  tasks:
  - name: Bastion replace DNS1
    lineinfile:
      path: /etc/named.conf
      regexp: "        listen-on port 53 { 127.0.0.1; };"
      line: "        listen-on port 53 { any; };"
      state: present
#    with_items:
#      - { regexp: "^        listen-on port 53 ", replace: "        listen-on port 53 { any; };" }
#      - { regexp: "^        listen-on-v6 port 53 ", replace: "        listen-on-v6 port 53 { any; };" }
#      - { regexp: "^        allow-query ", replace: "        allow-query  { any; };" }
