---
- name: Job for Bastion
  become: yes
  hosts: controller
  tasks:
  - name: Bastion replace DNS1
    replace:
      path: /etc/named.conf
      regexp: "{{ item.regexp }}"
      before: "{{ item.before }}"
      after: "{{ item.after }}"
    with_items:
      - { regexp: "^(.+)$", before: "127.0.0.1", after: "any" }
      - { regexp: "^(.+)$", before: "::1", after: "any" }
      - { regexp: "^(.+)$", before: "localhost", after: "any" }
